### ISSUE TITLE
em-serialport gem build problem

### ISSUE THREAD

**Issue by xtalker** [railsbob/em-serialport#2]
Can't seem to install on Raspberry Pi?

Ruby: ruby 1.9.3p194 (2012-04-20 revision 35410) [arm-linux-eabihf]
Linux version 3.2.27+ (dc4@dc4-arm-01)

 $ sudo gem install em-serialport
Building native extensions.  This could take a while...
ERROR:  Error installing em-serialport:
        ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_thread_check_ints()... yes
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for main() in -lcrypto... no
creating Makefile

make
compiling files.cpp
compiling binder.cpp
compiling sigs.cpp
compiling emwin.cpp
compiling rubymain.cpp
rubymain.cpp: In function âVALUE t_connect_server(VALUE, VALUE, VALUE)â:
rubymain.cpp:468:42: error: format not a string literal and no format arguments [-Werror=format-security]
rubymain.cpp: In function âVALUE t_bind_connect_server(VALUE, VALUE, VALUE, VALUE, VALUE)â:
rubymain.cpp:488:42: error: format not a string literal and no format arguments [-Werror=format-security]
cc1plus: some warnings being treated as errors
make: *** [rubymain.o] Error 1

**Comment by padcom** [comment]
@sdesbure That pull request you made worked for me - thanks!
